services:
  fast-app:
    image: trapper137/fast-app:latest
    ports:
      - "${WEBUI_PORT_FAST_APP}:8000"
    environment:
      - OLLAMA_ENDPOINT=${OLLAMA_LLM_API_BASE}
      - OLLAMA_MODEL=${OLLAMA_LLM_MODEL}
      - RESUME_API_KEY=${RESUME_API_KEY}
      - RESUME_ENDPOINT=${REACTIVE_RESUME_FRONTEND_BASE_URL}
    volumes:
      - ${FOLDER_FOR_CONFIGS}/fast-app/config.json:/app/config.json:ro
      - ${FOLDER_FOR_CONFIGS}/fast-app/profile.json:/app/profile.json:ro
      - ${FOLDER_FOR_CONFIGS}/fast-app/base-resume.json:/app/base-resume.json:ro
      - ${FOLDER_FOR_CONFIGS}/fast-app/base-cover-letter.json:/app/base-cover-letter.json:ro
      - ${FOLDER_FOR_CONFIGS}/fast-app/output:/app/output
      - ${FOLDER_FOR_CONFIGS}/fast-app/.fast-app:/root/.fast-app
    restart: unless-stopped